- name: install the nginx
  ansible.builtin.package:
     name: nginx
     state: present
  
- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: delete the file 
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: include common role
  include_role:
   name: common
   tasks_from: main

# - name: create a new file
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/
#     state: directory

# - name: Download a frontend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: Extract the code from url
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: copy the expense config file
  ansible.builtin.template:
   src: expense.conf.j2
   dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx

 
