- name: Install the mysql-server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Start and enable the mysql-server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install the python libs
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: connect to mysqld 
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: "{{ My_host }}"
  register: mysql_result
  ignore_errors: true

- name: print the output
  ansible.builtin.debug:
    msg: "mysql result is {{ mysql_result }}"

- name: setting the mysql root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_password }}"
  when: mysql_info.failed is true